### ISSUE TITLE
How do I stop a download?

### ISSUE THREAD

**Issue by tyeeman** [tardisx/gropple#10]
Just trying this out. Looks nice, but how to stop a download? I went to a youtube page with lots of videos listed and started a download and gropple started to download all the videos. Had to terminate it to stop it. I have another site I use that lists a whole bunch of videos and normally when I click one it starts downloading. How do I do that with Gropple (only select one of many)?

**Comment by tardisx** [comment]
This is a good idea. I will add a "stop download" button.

With respect to playlists, when youtube-dl (or fork) downloads more than one file from a single URL, it handles the playlist listing and iteration over the downloads. At the moment gropple is simply letting it "do it's thing" and download them all, indiscriminately.

It is possible to do better - youtube-dl has options to just download the playlist data, which could then spawn multiple jobs, or provide some way of selecting them individually.

Out of scope here, but I'm open to it being a suggestion.

**Comment by tyeeman** [comment]
OK, thanks. I just read the instructions again and was wondering if after this step - 

`So, whenever you are on a page with a video you would like to download just click the bookmarklet`

After clicking the bookmark is it easy to add a list of all the videos on the page with a checkbox beside each one and then we just select which one(s) we want?

**Comment by tyeeman** [comment]
BTW, I checked out your website and it's very nice. Clean for sure. I'm constantly looking for static site blog software so just wondering what you use. My criteria include having tags, and yours does! Is it written in GO? That's what I like nowadays. One exe does it all!

**Comment by tardisx** [comment]
In v0.5.4 you can now stop a download in progress.

This is not the same as being able to selectively download from a playlist, but #11 is open for that.
