### ISSUE TITLE
config gropple portable

### ISSUE THREAD

**Issue by candrapersada** [tardisx/gropple#13]
why is `config.yml` not saved in the same folder as `gropple.exe`?

**Comment by tardisx** [comment]
It's pretty standard behaviour to store a config file in $HOME or similar, so the binary can be anywhere. What's your use case?

**Comment by candrapersada** [comment]
how to save `config.yml` in a portable folder so it's easy to use gropple without config from scratch again.

**Comment by tardisx** [comment]
Do you mean you want to run it from a USB stick or similar? On multiple machines?

**Comment by candrapersada** [comment]
> Do you mean you want to run it from a USB stick or similar

yes

> On multiple machines?

yes

**Comment by soulmaestro** [comment]
pfff code-block insert is sh**t, oh well you should be able to figure it out with the above info
