### ISSUE TITLE
"Could not find yt-dlp on the path" error

### ISSUE THREAD

**Issue by DraconicBlaze28** [tardisx/gropple#19]
No matter what I try, I get this error. I'm a little unsure as to where you're supposed to specify the path to the downloader, so  I tried everything I could think of. I tried setting the download path to where yt-dlp was installed, I tried setting it in the "command to run section" none of it worked. What am I doing wrong?

**Comment by tardisx** [comment]
Hey @DraconicBlaze28 , will need more details to know.

How and where is yt-dlp installed? 

How do you run gropple? 

What platform are you on?

**Comment by DraconicBlaze28** [comment]
Hi, thanks for taking the time to reply and help me with this. I am on the Steam Deck, so ArchLinux. I installed yt-dlp through pip, which installed it to /home/deck/miniconda3/lib/python3.7/site-packages/yt_dlp/.  I run gropple by right-clicking on the file and selecting "run in Konsole"

**Comment by tardisx** [comment]
ok, so can you run "/home/deck/miniconda3/lib/python3.7/site-packages/yt_dlp/yt_dlp"  from the command line?

If so, you should be able to use that same fully qualified path in gropple.

I don't know why pip is installing the binary to such a strange place, but it seems unlikely to be on your path.

If that doesn't work, at a prompt, can you try just running "yt-dlp" ? If that works, then running "which yt-dlp" will tell you the full path to use in gropple.

**Comment by DraconicBlaze28** [comment]
Ah, that worked. Thank you so much.
