### ISSUE TITLE
configurable options for youtube-dl, or the ability to use various youtube-dl forks

### ISSUE THREAD

**Issue by tardisx** [tardisx/gropple#5]

**Comment by tardisx** [comment]
Basic configurability is in release 0.03

**Comment by DarrenPIngram** [comment]
Nice, thanks. Would it be possible (for those running the executable version) to have an option within the "browser" to change the yt-* downloader, aka a preference pane within the port 6283 "web server" ? Will have a play generally with the command line version later too.

**Comment by tardisx** [comment]
Agreed @DarrenPIngram , I created issue #7 for that :-)

**Comment by tardisx** [comment]
Hi @DarrenPIngram, the just released v0.5.0 should fully support your needs now.

**Comment by DarrenPIngram** [comment]
Will give it a whirl later today or tomorrow. Appreciate your efforts and
the personal "heads up!"-

‌
