### ISSUE TITLE
on windows failed to download

### ISSUE THREAD

**Issue by siranggiting** [tardisx/gropple#6]
start of log...
error starting youtube-dl: exec: "youtube-dl": executable file not found in %PATH%

**Comment by tardisx** [comment]
Is youtube-dl installed? As per the readme you will have to install it separately. 

If it is installed, can you run it from a command prompt?

**Comment by siranggiting** [comment]
My bad. I forgot to do pip install youtube_dl
Thanks for helping. I have use it. I open from firefox and gropple some video. I got 3 files which is .info.json, .mp4, and .m4a
From those files, I got .mp4 file is a video but no audio and .m4a file is an audio but no video. 

At first I thought my media player is broken, but I try to open other .mp4 files di my disk and I had both video and audio. 

Sory for my english so bad.

**Comment by tardisx** [comment]
Great to hear! If you also install ffmpeg, youtube-dl will remux the mp4 and m4a back into a single file.
