### ISSUE TITLE
No popup on certain sites

### ISSUE THREAD

**Issue by ghost** [tardisx/gropple#9]
On some sites the popup doesn't show up while Youtube and various other sites work perfectly fine.

I'm using the latest version of Chrome 95.0.4638.54.
No Ad blocker, no errors in the console (Chrome / F12)

Some examples where it doesn't work:
https://www.pornhub.com/
https://de.spankbang.com/

Would highly appreciate if someone could look into this as gropple seems to be the perfect solution for my needs.

**Comment by tardisx** [comment]
Hi @Gishanx 

Can you please clarify, when you say "doesn't show up" do you mean that it doesn't even open the popup window at all, or that the popup window is empty?

I'm a little confused if it's the former - as that part (the actual window opening) is 100% client side javascript encoded into the bookmarklet, and that will even work if gropple isn't running.

I've managed to successfully gropple videos from both those sites with Chrome (Mac).

**Comment by tardisx** [comment]
No dramas, thanks for investigating. It’s worth me putting a note on the page to help avoid others hitting the same problem. Thanks!
